### ISSUE TITLE
Case sensitivity

### ISSUE THREAD

**Issue by bbuehrle** [mattermost/mattermost-plugin-profanity-filter#11]
Is there a flag to set that would ignore case-sensitivity?  The filter censors `f***` but leaves `F***` alone.

**Comment by hanzei** [comment]
Good suggestion @bbuehrle :+1:

**Comment by bbuehrle** [comment]
I've never used Go before and I couldn't even get it to build.  From what I can tell, maybe...

```
func (p *Plugin) OnActivate() error {
	p.badWords = make(map[string]bool, len(badWords))
	for _, word := range badWords {
/** make sure all words in array are lower case */
                word := string.ToLower(word)
		p.badWords[word] = true
	}

	return nil
}
```

```
func (p *Plugin) WordIsBad(word string) bool {
/** make sure word to be compared is lower case */
        word := string.ToLower(word)
	_, ok := p.badWords[word]
	return ok
}
```

Would something like this work?

**Comment by hanzei** [comment]
Yes, that would work :+1:

**Comment by hanzei** [comment]
Let's keep this open until https://github.com/mattermost/mattermost-plugin-profanity-filter/pull/12 is merged

**Comment by bbuehrle** [comment]
Good deal.  Do you know when that may be?

**Comment by hanzei** [comment]
Your PR is awaiting review from @iomodo, but once that is done, we can merge it.

**Comment by bbuehrle** [comment]
Thanks, @hanzei. Do you know when the next release will be?  Looks like the last one was 18 months ago.

**Comment by hanzei** [comment]
I'm not sure @bbuehrle. But if you really want that new version, you can just build it yourself from source.
