### ISSUE TITLE
Edit badwords list from settings

### ISSUE THREAD

**Issue by nathanaelhoun** [mattermost/mattermost-plugin-profanity-filter#13]
Is it possible to make the bad words list editable from the plugin settings in the admin console ?

It would be easier to quickly add a word to the list

**Comment by nathanaelhoun** [comment]
Hi, I want to work on this :-)

**Comment by hanzei** [comment]
Thanks @nathanaelhoun :+1:

**Comment by fshaikh4** [comment]
Hello there,

I am using Mattermost 5.25.0, and we wanted to use this plugin and customize the "bad words list". In the documentation it mentions that this is doable via the plugin menu in the Mattermost UI, but I cannot seem to find this setting:

![image](https://user-images.githubusercontent.com/10870607/90291411-dffd7800-de4d-11ea-8866-bc62b04d20e5.png)

Is this feature reflected in the latest release I downloaded from here on GitHub?

**Comment by hanzei** [comment]
Hi @fshaikh4,
What version of the plugin are you running?

**Comment by fshaikh4** [comment]
I believe it is 0.10, the latest from the releases section of this site

**Comment by fshaikh4** [comment]
> I believe it is 0.10, the latest from the releases section of this site

sorry, 0.1.0

**Comment by hanzei** [comment]
Good catch @fshaikh4. The UI update isn't in a release yet. I've filled https://github.com/mattermost/mattermost-plugin-profanity-filter/issues/16 to track cutting a new release.

You can still build the plugin from `master` yourself if you don't want to wait for the relesae.
