### ISSUE TITLE
Unable to download according to README.MD

### ISSUE THREAD

**Issue by uhlhosting** [mattermost/mattermost-plugin-profanity-filter#2]
There aren’t any releases here
Releases are powered by tagging specific points of history in a repository. They’re great for marking release points like v1.0.

**Comment by amyblais** [comment]
Hi @uhlhosting - I believe this will be available in v5.2 which is released next month.

**Comment by uhlhosting** [comment]
@amyblais thank you for the update.

**Comment by crspeller** [comment]
I created a release. You can find it on the github releases page for this repository. Note that it requires Mattermost server v5.2
