### ISSUE TITLE
Change word list to be coma delimited instead of space delimited

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-profanity-filter#20]
The word list is currently space delimited. This is not ideal because in some cases "bad word" should be filtered but "bad" and "word" are not offensive at all in a different context when not next to each other. 

This should be coma delimited so users can specify to filter on "bad word" but users can post "bad" or "word".  

Note that the current list already includes terms that have spaces in them which would cause unexpected words to be blocked.

**Comment by hanzei** [comment]
Makes sense to me. @nathanaelhoun What do you think?

**Comment by nathanaelhoun** [comment]
Its sounds like a great addition to me. If we use a regex match in the post content as suggested in #22 (instead of a space-delimited split), it should be easy to make this change.

**Comment by hanzei** [comment]
@nathanaelhoun Are you interested in working on this?

**Comment by aaronrothschild** [comment]
Thanks for this contribution @nathanaelhoun , you're on a roll!
