### ISSUE TITLE
Reject Posts option should give feedback explaining that it is related to the post content

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-profanity-filter#21]
Reject Posts give no feedback as to why the post was rejected. It is indistinguishable from some type of connectivity issue. 

When the plugin rejects a post because the feature is enabled, it should show an ephemeral post explaining that the content of the post was rejected because it contains unacceptable terms.

**Comment by hanzei** [comment]
Good suggestion @DHaussermann. @nathanaelhoun I'm wondering if you are interested in working on this?
