### ISSUE TITLE
Profanity filter should ignore punctuation when looking for profanity 

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-profanity-filter#22]
Currently the profanity filter only looks for words that are an exact match on the "Bad words list" and nothing with punctuation is filtered out. So if I type "expletive" it will get filtered by the pluign but, "expletive!" or "expletive." with the punctuation, the filter has no affect. 

Because it very common, we need to be able to filter words that are followed by punctuation. Maybe we could use some type of regex match instead?

**Comment by hanzei** [comment]
That is a good suggestion. It will require some refactoring for the plugin, but it will make it more resilient. 

@nathanaelhoun I know you are also working on two other issue, but I'm sill wondering if you also want to pickup this?

**Comment by nathanaelhoun** [comment]
Yes @hanzei, I will work on this when resolving #22, as theses issues are related. I have already begun and will submit a PR in a few days

**Comment by hanzei** [comment]
Amazing! Thanks for driving these changes. Looking forward to your PR @nathanaelhoun
