### ISSUE TITLE
Disable for plugins posts

### ISSUE THREAD

**Issue by nathanaelhoun** [mattermost/mattermost-plugin-profanity-filter#25]
Sometimes posts created by plugins/integrations are rejected by the plugin.
It's hard to understand for the user because he doesn't see any track for this (we can just see this in the server logs).

**Comment by hanzei** [comment]
Is there a way to check if a post was made by a plugin? Or do you suggest check if it's made from a bot?

**Comment by nathanaelhoun** [comment]
Check if it's made from a bot is fine I think (and maybe better as it will also work for integrations)

**Comment by n-thumann** [comment]
I´d like to work on this issue, if you don´t mind ✌️

**Comment by hanzei** [comment]
Thanks @n-thumann :+1:
